/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SzakemberekRouteImport } from './routes/szakemberek'
import { Route as KlimakIndexRouteImport } from './routes/klimak.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SzakemberekRoute = SzakemberekRouteImport.update({
  id: '/szakemberek',
  path: '/szakemberek',
  getParentRoute: () => rootRouteImport,
} as any)
const KlimakIndexRoute = KlimakIndexRouteImport.update({
  id: '/klimak/',
  path: '/klimak/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/szakemberek': typeof SzakemberekRoute
  '/klimak/': typeof KlimakIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/szakemberek': typeof SzakemberekRoute
  '/klimak': typeof KlimakIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/szakemberek': typeof SzakemberekRoute
  '/klimak/': typeof KlimakIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/szakemberek' | '/klimak/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/szakemberek' | '/klimak'
  id: '__root__' | '/' | '/szakemberek' | '/klimak/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SzakemberekRoute: typeof SzakemberekRoute
  KlimakIndexRoute: typeof KlimakIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/szakemberek': {
      id: '/szakemberek'
      path: '/szakemberek'
      fullPath: '/szakemberek'
      preLoaderRoute: typeof SzakemberekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klimak/': {
      id: '/klimak/'
      path: '/klimak'
      fullPath: '/klimak/'
      preLoaderRoute: typeof KlimakIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SzakemberekRoute: SzakemberekRoute,
  KlimakIndexRoute: KlimakIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
